server.port=${PORT:8080}

# --- Cloud In-Memory Database (Active) ---
spring.datasource.url=jdbc:h2:mem:helpsystemsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# --- DELETE THESE LINES BELOW OR ADD A '#' BEFORE THEM ---
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/helpsystemdb}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
# spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
# spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
ml.api.url=${ML_API_URL:http://localhost:5000/predict}
